### ISSUE TITLE
Completing the assignment

### ISSUE THREAD

**Issue by snavetrain** [snavetrain/Group-Project-2#12]
We need to edit each others content units according to the directions.  Two people need to have edited each content unit. 

Thanks team BlazeBoi's

**Comment by patr-tam** [comment]
I got an email saying I was assigned #12, where is it?

**Comment by snavetrain** [comment]
What do you mean by #12? 

"An important part of social coding is learning to resolve conflicts that arise when multiple people make conflicting changes to the same file; therefore, a requirement is that each content unit contain edits by at least two members of the team. I will be looking at the Github logs to see how these conflict situations are resolved. You should use the collaboration tools provided by Github to assist (such as Pull requests, and the Conversation mechanism that is provided). If these situations don’t naturally occur in your project, engineer them."

**Comment by patr-tam** [comment]
Oh, I think this issue was labeled #12 for some reason.

**Comment by snavetrain** [comment]
Oh I see, well we can go through the code changes and see which units need editing! Mine is good since @coronado17 edited the spurs pic.

**Comment by patr-tam** [comment]
Well I edited one of the images because it wasn't aligning correctly but it looks fine when viewed through actual web page. Preview page was a bit different.
